### ISSUE TITLE
UI changes for diagnostics master issue

### ISSUE THREAD

**Issue by dangunter** [IDAES/idaes-ui#42]
This issue provides a list of tasks for implementing the new design expressed in mockups (attached).
The list of tasks may grow and change. They are listed here in order of operations (i.e. do the first one first).
Please create PRs for each, add the number, and check off when merged.

- [x] Rewrite backend API tests for FastAPI *Sheng: WIP* (#43) 
- [x] Create smoke tests that operate on the header area of the page
- [x] Add [react mosaic](https://github.com/nomcopter/react-mosaic) (RM) to make panel layout flexible (GL dropped react support) *Sheng: WIP *
- [x] Add tests for RM
- [x] Add diagnostics panel with structural issues tab (only), no "suggested next steps" *Sheng: WIP* (#34)

target for Jan 30th meeting

----
- [x] Add numerical issues tab to diagnostics panel, no suggested next steps
- [x] Add suggested next steps APIs and tests
- [x] Add suggested next steps output panel, and links in both structural issues and numerical issues panels
- [ ] Add side panel with unit performance information
- [ ] Add "brushing" between diagram and diagnostics - re-run diagnostics on selected unit
- [ ] Add "brushing" between diagram/diagnostics/side panel with unit info

![Flowsheet Visualizer Mockups (1)](https://github.com/IDAES/idaes-ui/assets/420923/d367401a-10e9-41a4-8700-73aa2b4bb602)

**Comment by CopyDemon** [comment]
FastAPI main feature is finished, and working now, try to fix the CI workflow file to let GitHub trigger the CI correctly.

**Comment by CopyDemon** [comment]
Display config and diagnostics result functions have finished on PR #34  Try to find the "suggested next step" data in the diagnostics JSON.

**Comment by CopyDemon** [comment]
Golden layout is dropped react support, [Golden dropped feature doc](https://golden-layout.github.io/golden-layout/version-2/)

Now find an alternative layout manager:
[react-mosaic](https://github.com/nomcopter/react-mosaic)
